### ISSUE TITLE
feat: example templates for fast development

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku-examples#271]
This is a **feature request**

## Problem

We have a set of examples that are based on the same code and other examples are not coherent. 
In the future, I anticipate more examples being created for the reason of showcasing new functionality.
Due to that, it can become messy fast and a developer will have to re-create everything from scratch. 

## Proposed Solutions

To save time a set of templates should be created. They can be copy-pasted when new example have to be created. 
Criteria for a template are:
- [ ] Modular - should have UI and logic be split;
- [ ] Simple - should cover basic `waku` functionality inside;
- [ ] Extendable - should be easy to add new features, add packages, upgrade old;

## Tasks

- [ ] Create template for plain JS ([light chat](https://github.com/waku-org/js-waku-examples/tree/master/examples/light-chat) should be used here);
- [ ] Create template for React;
- [ ] Create template for Svelte with Vite; 
- [ ] Create template for Vue or Angular;

**Comment by weboko** [comment]
upd: added NextJS as needed template based on hacker's feedback

**Comment by chair28980** [comment]
cc @hackyguru @vpavlin 

This might fall under the @waku-org/eco-dev realm.
