### ISSUE TITLE
Migrate examples here

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku-examples#94]
## Tasks

- [x] Move status-im/js-waku-examples to waku-org orga
- [x] Setup Jenkins to publish js-waku-examples to examples.waku.org
- [x] Update js-waku-examples to latest code from js-waku repo
- [x] Remove Jenkins setup to publish js-waku/examples to https://js-waku.wakuconnect.dev/examples
- [x] Update documentation to point to new url
- [x] Remove examples folder from js-waku repo
- [x] Get content for examples.waku.org (eg. redirect to js.waku.guide/docs/examples)

**Comment by fryorcraken** [comment]
@jakubgs can you please published the various folders in this repo to https://examples.waku.org?

This is the same than https://github.com/status-im/js-waku/blob/master/ci/Jenkinsfile.gh-pages

As per steps above, I will then delete https://github.com/status-im/js-waku/blob/master/ci/Jenkinsfile.gh-pages and https://github.com/status-im/js-waku/tree/master/examples

Thanks!

**Comment by jakubgs** [comment]
Okay, but is there's no main page for this as far as I can see.

**Comment by fryorcraken** [comment]
> Okay, but is there's no main page for this as far as I can see.

Noted. Please proceed, will add to future tasks.

**Comment by jakubgs** [comment]
But... what should be on the main page for now? Just 404 error?

**Comment by fryorcraken** [comment]
> But... what should be on the main page for now? Just 404 error?

Just 404 please.

**Comment by jakubgs** [comment]
The `eth-pm` example appears to be broken:
```
+ yarn run build
yarn run v1.22.19
$ react-scripts build
Creating an optimized production build...
Failed to compile.

TS2345: Argument of type 'ArrayBuffer' is not assignable to parameter of type 'Uint8Array'.
  Type 'ArrayBuffer' is missing the following properties from type 'Uint8Array': BYTES_PER_ELEMENT, buffer, byteOffset, copyWithin, and 24 more.
    14 |     salt: utils.bytesToHex(salt),
    15 |     iv: utils.bytesToHex(iv),
  > 16 |     cipher: utils.bytesToHex(cipher),
       |                              ^^^^^^
    17 |   };
    18 |
    19 |   localStorage.setItem("cipherEncryptionKeyPair", JSON.stringify(data));
```
I'll comment it out for now.

**Comment by jakubgs** [comment]
The site builds have been failing because of this since 8th of August:

![image](https://user-images.githubusercontent.com/2212681/188712066-9ea33c12-b3ac-4240-8cde-c9f8f6f84cb4.png)

**Comment by jakubgs** [comment]
Created the CNAME: https://github.com/status-im/infra-misc/commit/4f80ea3d

**Comment by jakubgs** [comment]
Well, the first version works: https://examples.waku.org/web-chat/

**Comment by fryorcraken** [comment]
@jakubgs looks like the Jenkins build hasn't run since 7 September: https://ci.infra.status.im/job/website/job/examples.waku.org/

Am I missing something?

**Comment by jakubgs** [comment]
Btw, because there's no `yarn.lock` files the `yarn install` step is about 5x slower:

![image](https://user-images.githubusercontent.com/2212681/189925420-356c5ff4-293a-4527-b8a0-06714878b79d.png)

**Comment by fryorcraken** [comment]
> Btw, because there's no `yarn.lock` files the `yarn install` step is about 5x slower:

Yes I know, I personally don't really mind. Is it an issue on your side?

**Comment by jakubgs** [comment]
Not really, just pointing it out. Tell me if this happens again. I'm not 100% sure it was fixed.

**Comment by fryorcraken** [comment]
One task remaining

**Comment by fryorcraken** [comment]
@hackyguru are you happy to take this over? the root page: https://examples.waku.org returns a 404, we need to decide what it should return/direct too and do it or get help from Comms Hub.

**Comment by hackyguru** [comment]
@fryorcraken Assigned the issue to myself. I'll get this done and request for a review

**Comment by hackyguru** [comment]
For the time being, [examples subdomain](https://examples.waku.org/) is being redirected to [examples section of waku guide](https://js.waku.guide/docs/examples). We can revamp this once we have our refactored docs in coming weeks
